# Generated by Django 2.0.3 on 2018-03-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_elo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='pub_date',
            new_name='elo_date',
        ),
    ]
